// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBavITP-DUOc5fuw9fA_r2c3sdjYwRzjDI',
    appId: '1:725245604497:web:74794486935b08f169c530',
    messagingSenderId: '725245604497',
    projectId: 'ai-stock-analyzer-ea263',
    authDomain: 'ai-stock-analyzer-ea263.firebaseapp.com',
    storageBucket: 'ai-stock-analyzer-ea263.firebasestorage.app',
    measurementId: 'G-7RNB2B0PPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtOBc8b4qFDgBx_pro6tqKkKFnxe-9XHg',
    appId: '1:725245604497:android:35ea8756712b731369c530',
    messagingSenderId: '725245604497',
    projectId: 'ai-stock-analyzer-ea263',
    storageBucket: 'ai-stock-analyzer-ea263.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNs22XnMD-vVZIo6cvUTw-wpUc3neEUws',
    appId: '1:725245604497:ios:670f34692842fad969c530',
    messagingSenderId: '725245604497',
    projectId: 'ai-stock-analyzer-ea263',
    storageBucket: 'ai-stock-analyzer-ea263.firebasestorage.app',
    iosBundleId: 'com.example.aiStockAnalyzer',
  );
}
